/**
 * One-off script: builds en.json and kk.json from ru.json using path-based overrides.
 * Run: node scripts/apply-en-kk.mjs
 */
import fs from 'fs'
import { fileURLToPath } from 'url'
import { dirname, join } from 'path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = join(__dirname, '..')
const ru = JSON.parse(fs.readFileSync(join(root, 'src/locales/ru.json'), 'utf8'))

function deepClone(o) {
  return JSON.parse(JSON.stringify(o))
}

function walkLeaves(obj, prefix, fn) {
  for (const k of Object.keys(obj)) {
    const p = prefix ? `${prefix}.${k}` : k
    const v = obj[k]
    if (v && typeof v === 'object' && !Array.isArray(v)) walkLeaves(v, p, fn)
    else fn(p, v)
  }
}

function applyOverrides(base, overrides) {
  const out = deepClone(base)
  walkLeaves(out, '', (path) => {
    if (overrides[path] !== undefined) {
      const parts = path.split('.')
      let cur = out
      for (let i = 0; i < parts.length - 1; i++) cur = cur[parts[i]]
      cur[parts[parts.length - 1]] = overrides[path]
    }
  })
  return out
}

/** @type {Record<string, string>} */
const en = {}
/** @type {Record<string, string>} */
const kk = {}

walkLeaves(ru, '', (path, value) => {
  if (typeof value !== 'string') return
  en[path] = value
  kk[path] = value
})

// --- English overrides (all leaf paths from ru.json) ---
const enOverrides = {
  'a11y.languageMenu': 'Language',
  'a11y.openMenu': 'Open menu',
  'a11y.close': 'Close',
  'nav.features': 'Features',
  'nav.howItWorks': 'How it works',
  'nav.about': 'About',
  'nav.profile': 'Profile',
  'nav.logout': 'Log out',
  'nav.login': 'Log in',
  'nav.register': 'Sign up',
  'nav.dashboard': 'Dashboard',
  'nav.map': 'Map',
  'nav.createRequest': 'Create request',
  'nav.myRequests': 'My requests',
  'nav.requests': 'Requests',
  'nav.volunteers': 'Volunteers',
  'nav.incidents': 'Incidents',
  'nav.myTasks': 'My tasks',
  'nav.admin': 'Admin',
  'nav.adminOverview': 'Overview',
  'nav.adminUsers': 'Users',
  'nav.adminRequests': 'Requests',
  'nav.adminIncidents': 'Incidents',
  'nav.mainSite': 'Main site',
  'footer.tagline': 'A platform for coordinating aid during emergencies',
  'footer.platform': 'Platform',
  'footer.roles': 'Roles',
  'footer.contacts': 'Contacts',
  'footer.copyright': '© 2026 DisasterHelp. All rights reserved.',
  'footer.forUsers': 'For users',
  'footer.forVolunteers': 'For volunteers',
  'footer.forCoordinators': 'For coordinators',
  'footer.howWorks': 'How it works',
  'footer.registration': 'Sign up',
  'home.heroLine1': 'Fast coordination of aid',
  'home.heroLine2': 'during emergencies',
  'home.heroDescription':
    'A centralized platform for collecting help requests, assigning volunteers, and tracking assistance during emergencies',
  'home.createHelp': 'Create a help request',
  'home.becomeVolunteer': 'Become a volunteer',
  'home.statActive': 'Active requests',
  'home.statVolunteers': 'Volunteers',
  'home.statHelped': 'People helped',
  'home.urgent': 'Urgent',
  'home.demoCardTitle': 'Medical assistance needed',
  'home.demoLocation': 'Almaty, Abay Ave., 150',
  'home.minsAgo': '{n} min ago',
  'home.statusNew': 'New',
  'features.title': 'Platform features',
  'features.description': 'Everything you need to coordinate aid effectively in one place',
  'features.f1t': 'Help requests',
  'features.f1d': 'Create and manage requests with problem type and location',
  'features.f2t': 'Interactive map',
  'features.f2d': 'See all requests on the map with filters by status and type',
  'features.f3t': 'Volunteer management',
  'features.f3d': 'Register volunteers, assign tasks, and track activity',
  'features.f4t': 'Resource management',
  'features.f4d': 'Track and distribute material resources for aid',
  'features.f5t': 'Notifications',
  'features.f5d': 'Alerts via Telegram bot for new requests and updates',
  'features.f6t': 'Status tracking',
  'features.f6d': 'Monitor how assistance is delivered in real time',
  'howItWorks.title': 'How it works',
  'howItWorks.s1t': 'Create a request',
  'howItWorks.s1d': 'A person in need or a witness creates a request with details and location',
  'howItWorks.s2t': 'Coordination',
  'howItWorks.s2d': 'A coordinator reviews requests on the map and assigns volunteers',
  'howItWorks.s3t': 'Providing help',
  'howItWorks.s3d': 'A volunteer gets notified, arrives on site, and provides help',
  'howItWorks.s4t': 'Reporting',
  'howItWorks.s4d': 'Status is updated, help is marked complete, and the system keeps a record',
  'cta.title': 'Ready to help or get help?',
  'cta.subtitle': 'Join the platform and be part of the response system',
  'cta.start': 'Get started',
  'cta.learnMore': 'Learn more',
  'common.save': 'Save',
  'common.cancel': 'Cancel',
  'common.close': 'Close',
  'common.loading': 'Loading...',
  'common.loadingEllipsis': 'Loading…',
  'common.refresh': 'Refresh',
  'common.search': 'Search',
  'common.yes': 'Yes',
  'common.no': 'No',
  'common.backToList': '← Back to list',
  'common.open': 'Open',
  'common.edit': 'Edit',
  'common.delete': 'Delete',
  'common.total': 'Total: {n}',
  'common.pageOf': '{current} of {total}',
  'common.idColumn': 'ID',
  'common.all': 'All',
  'common.optional': 'Optional',
  'common.password': 'Password',
  'common.phone': 'Phone',
  'common.address': 'Address',
  'common.title': 'Title',
  'common.description': 'Description',
  'common.district': 'District',
  'common.priority': 'Priority',
  'common.status': 'Status',
  'common.type': 'Type',
  'common.actions': 'Actions',
  'common.created': 'Created',
  'common.published': 'Publication',
  'common.contact': 'Contact',
  'common.peopleCount': 'Number of people',
  'common.notSpecified': '— not specified —',
  'common.request': 'Request',
  'common.filters': 'Filters',
  'common.hideFilters': 'Hide filters',
  'common.showFilters': 'Show filters',
  'common.noData': 'No data',
  'common.error': 'Error',
  'common.success': 'Saved',
  'auth.loginTitle': 'Sign in',
  'auth.loginSubtitle': 'Enter your credentials to continue',
  'auth.rememberMe': 'Remember me',
  'auth.forgotPassword': 'Forgot password?',
  'auth.signIn': 'Sign in',
  'auth.noAccount': 'No account?',
  'auth.signUpLink': 'Sign up',
  'auth.registerTitle': 'Create account',
  'auth.registerSubtitle': 'Fill in the form to register',
  'auth.firstName': 'First name',
  'auth.lastName': 'Last name',
  'auth.confirmPassword': 'Confirm password',
  'auth.role': 'Role',
  'auth.selectRole': 'Select a role',
  'auth.roleUser': 'User (needs help)',
  'auth.roleVolunteer': 'Volunteer',
  'auth.roleCoordinator': 'Coordinator',
  'auth.agreeTerms': 'I agree to the {terms} and {privacy}',
  'auth.terms': 'terms of use',
  'auth.privacy': 'privacy policy',
  'auth.agreeDataProcessing': 'I agree to the processing of personal data for coordinating aid',
  'auth.registerSubmit': 'Sign up',
  'auth.hasAccount': 'Already have an account?',
  'auth.signInLink': 'Sign in',
  'auth.welcomeTitle': 'Welcome to DisasterHelp',
  'auth.welcomeSubtitle': 'A platform for coordinating aid during emergencies',
  'auth.feat1': 'Fast coordination of aid',
  'auth.feat2': 'Manage requests and volunteers',
  'auth.feat3': 'Track statuses in real time',
  'auth.forgotTitle': 'Reset password',
  'auth.forgotDesc': 'Enter your account email — we will send a reset link.',
  'auth.send': 'Send',
  'auth.verifiedSuccess': 'Email verified. Please sign in.',
  'auth.loginError': 'Sign-in failed. Please try again.',
  'auth.registerSuccess': 'Registration successful. Check your email to verify.',
  'auth.registerError': 'Registration failed. Please try again.',
  'auth.forgotSent': 'Check your email — we sent a password reset link.',
  'auth.forgotError': 'Could not send the email. Check the address or try later.',
  'notFound.title': 'Page not found',
  'notFound.text': 'The page does not exist or has been moved.',
  'notFound.home': 'Home',
  'resetPassword.invalidLinkTitle': 'Invalid link',
  'resetPassword.invalidLinkText': 'The reset link is missing or expired. Request a new one.',
  'resetPassword.toLogin': 'Go to sign-in',
  'resetPassword.requestNew': 'Request a new link',
  'resetPassword.toLoginShort': 'Sign in',
  'resetPassword.invalidTokenTitle': 'Invalid link',
  'resetPassword.invalidTokenText':
    'The password reset link is invalid or expired. Request a new link on the sign-in page (“Forgot password?”).',
  'resetPassword.serverErrorTitle': 'Server error',
  'resetPassword.serverErrorText':
    'Could not verify the link. Try later or request a new password reset link.',
  'resetPassword.newPasswordTitle': 'New password',
  'resetPassword.newPasswordSubtitle': 'Enter a new password for your account.',
  'resetPassword.newPasswordLabel': 'New password',
  'resetPassword.repeatPassword': 'Repeat password',
  'resetPassword.savePassword': 'Save password',
  'resetPassword.backToLogin': 'Back to sign-in',
  'resetPassword.successCanLogin': 'You can now sign in with your new password.',
  'resetPassword.successChanged': 'Password changed successfully.',
  'resetPassword.successChangedLogin': 'Password changed. Please sign in with the new password.',
  'resetPassword.saveError': 'Could not save the password. The link may have expired.',
  'dashboard.title': 'Dashboard',
  'dashboard.subtitle': 'Activity and requests overview',
  'dashboard.notifications': 'Notifications',
  'dashboard.activeRequests': 'Active requests',
  'dashboard.myRequestsStat': 'My requests',
  'dashboard.usersTotal': 'Users',
  'dashboard.volunteersOnline': 'Volunteers online',
  'dashboard.inSystem': 'Total in the system',
  'dashboard.readyToHelp': 'Ready to help',
  'dashboard.doneToday': 'Completed today',
  'dashboard.requestsClosed': 'Requests closed',
  'dashboard.unverified': 'Unverified',
  'dashboard.urgentStat': 'Urgent',
  'dashboard.emailNotVerified': 'Email not verified',
  'dashboard.needAttention': 'Need attention',
  'dashboard.recentRequests': 'Recent requests',
  'dashboard.filterAll': 'All',
  'dashboard.filterUrgent': 'Urgent',
  'dashboard.filterNew': 'New',
  'dashboard.loadingRequests': 'Loading requests...',
  'dashboard.noRequests': 'No requests.',
  'dashboard.createRequestLink': 'Create request',
  'dashboard.volunteers': 'Volunteers',
  'dashboard.allLink': 'All',
  'dashboard.volunteerFallback': 'Volunteer',
  'dashboard.noVolunteers': 'No volunteer data',
  'dashboard.activeIncidents': 'Active incidents',
  'dashboard.noIncidents': 'No active incidents',
  'dashboard.activity': 'Activity',
  'dashboard.timeAgoMins': '{n} min ago',
  'dashboard.timeAgoHours': '{n} h ago',
  'dashboard.timeAgoDays': '{n} d ago',
  'dashboard.act1': 'Request <strong>#1247</strong> completed by volunteer Alex K.',
  'dashboard.act2': 'New request <strong>Medical aid</strong> in Abay district.',
  'dashboard.act3': 'Request <strong>#1240</strong> awaiting assignment for over 2 hours.',
  'dashboard.actTime1': '10 min ago',
  'dashboard.actTime2': '25 min ago',
  'dashboard.actTime3': '1 h ago',
  'map.searchPlaceholder': 'Search by address or description...',
  'map.createRequest': 'Create request',
  'map.priorityLegend': 'Priority',
  'map.show': 'Show',
  'map.allRequests': 'All requests',
  'map.mineRequests': 'My requests',
  'map.allDistricts': 'All districts',
  'map.allPriorities': 'All priorities',
  'map.allTypes': 'All types',
  'map.onMap': 'requests on map',
  'map.requestN': 'Request #{n}',
  'map.respond': 'Respond',
  'map.respondError': 'Could not respond',
  'map.people': 'Number of people',
  'mapPicker.label': 'Click the map to place a pin',
  'mapPicker.clear': 'Clear pin',
  'mapPicker.geocoding': 'Resolving address...',
  'mapPicker.clickHint': 'Click the map to set location',
  'createRequest.step1': 'Type of help',
  'createRequest.step2': 'Details',
  'createRequest.step3': 'Contacts',
  'createRequest.pageTitle': 'Create a help request',
  'createRequest.pageSubtitle':
    'Describe the situation — volunteers and coordinators will see the request on the map and can respond.',
  'createRequest.chooseType': 'Choose type of help',
  'createRequest.describe': 'Describe the situation',
  'createRequest.infoTitle': 'Provide the address and what is needed',
  'createRequest.infoText': 'The more detail you give, the faster help can arrive.',
  'createRequest.requestTitle': 'Request title',
  'createRequest.titlePlaceholder': 'Short summary (5–200 characters)',
  'createRequest.addressPlaceholder': 'Almaty, Abay Ave., 150',
  'createRequest.selectDistrict': 'Select district',
  'createRequest.descriptionPlaceholder':
    'Describe needs: number of people, conditions, urgency... (min. 50 characters)',
  'createRequest.contactsTitle': 'Contact details',
  'createRequest.yourName': 'Your name',
  'createRequest.namePlaceholder': 'John Doe',
  'createRequest.commentLabel': 'Optional (best time to call, notes)',
  'createRequest.next': 'Next',
  'createRequest.back': 'Back',
  'createRequest.submit': 'Submit request',
  'createRequest.submitError': 'Could not submit the request. Try later.',
  'createRequest.problemDescMedical': 'Injuries, medicines, doctors',
  'createRequest.problemDescFood': 'Food, drinking water, baby food',
  'createRequest.problemDescEvacuation': 'Transport, leaving the affected area',
  'createRequest.problemDescShelter': 'Temporary shelter, clothing',
  'createRequest.problemDescRepair': 'Electricity, heating, connectivity',
  'createRequest.problemDescPsychological': 'Support, counseling',
  'myRequests.title': 'My requests',
  'myRequests.subtitle': 'Requests you created. GET /requests/my',
  'myRequests.create': 'Create request',
  'myRequests.createFirst': 'Create your first request',
  'myRequests.empty': 'You have no requests yet.',
  'myRequests.published': 'Published',
  'myRequests.notPublished': 'Not published',
  'myRequests.onMap': 'On map',
  'myRequests.loadError': 'Could not load requests',
  'profile.changePhoto': 'Change photo',
  'profile.photo': 'Photo',
  'profile.photoAria': 'Choose a photo (JPG, PNG, or WebP)',
  'profile.photoHint': 'JPG, PNG, or WebP, up to 2 MB',
  'profile.editProfile': 'Edit profile',
  'profile.personal': 'Personal details',
  'profile.telegramPlaceholder': '@username or username',
  'profile.statistics': 'Statistics',
  'profile.requestsCreated': 'Requests created',
  'profile.doneAsVolunteer': 'Completed (as volunteer)',
  'profile.myRequests': 'My requests',
  'profile.noRequestsYet': 'You have not created any requests yet.',
  'profile.skills': 'Skills',
  'profile.deleteAccount': 'Delete account',
  'profile.deleteWarning': 'Deleting your account is permanent. Your requests and links will be removed.',
  'profile.deletePasswordLabel': 'Enter your password to confirm',
  'profile.deleteUnderstand': 'I understand my account and data will be permanently deleted',
  'profile.deleteSubmit': 'Delete account',
  'profile.deleting': 'Deleting...',
  'profile.activity': 'Activity',
  'profile.achievements': 'Achievements',
  'profile.editModalTitle': 'Edit profile',
  'profile.editModalHint':
    'You can change contact details (name, phone, district, Telegram) in the “Personal details” section below.',
  'profile.role': 'Role',
  'profile.avatarInvalidType': 'Only JPG, PNG, or WebP is allowed',
  'profile.avatarTooLarge': 'File size must be at most 2 MB',
  'profile.avatarUploadError': 'Could not upload photo',
  'profile.emailRequired': 'Enter email',
  'profile.emailSaved': 'Email saved. Confirm the new address via the link in the email.',
  'profile.emailSaveError': 'Could not save email',
  'profile.deleteError': 'Could not delete account',
  'profile.profileSaved': 'Profile saved',
  'profile.profileSaveError': 'Could not save profile',
  'profile.requestsLoadError': 'Could not load requests',
  'profile.skill1': 'First aid',
  'profile.skill2': 'Logistics',
  'profile.timeline1': 'Completed request <strong>#1247</strong> — medical aid.',
  'profile.timeline1t': '2 h ago',
  'profile.timeline2': 'Assigned to request <strong>#1248</strong> — evacuation.',
  'profile.timeline2t': 'Yesterday, 14:30',
  'profile.timeline3': 'Request <strong>#1240</strong> cancelled by coordinator.',
  'profile.timeline3t': 'Yesterday, 10:00',
  'profile.ach1Title': 'First response',
  'profile.ach1Desc': 'Responded to your first request',
  'profile.ach2Title': '10 completed tasks',
  'profile.ach2Desc': 'Completed 10 requests',
  'profile.ach3Title': 'Hero of the week',
  'profile.ach3Desc': 'Top 3 volunteer of the week',
  'incidents.title': 'Incidents',
  'incidents.subtitle': 'Emergencies: list, create, edit, change status',
  'incidents.create': 'Create incident',
  'incidents.allSeverities': 'All severities',
  'incidents.allStatuses': 'All statuses',
  'incidents.thSeverity': 'Severity',
  'incidents.thCreated': 'Created',
  'incidents.change': 'Change',
  'incidents.empty': 'No incidents',
  'incidents.modalCreateTitle': 'Create incident',
  'incidents.titlePlaceholder': '5–200 characters',
  'incidents.descPlaceholder': 'Minimum 20 characters',
  'incidents.severity': 'Severity',
  'incidents.select': 'Select',
  'incidents.createSubmit': 'Create',
  'incidents.modalEditTitle': 'Edit incident {id}',
  'incidents.saveError': 'Could not create incident',
  'incidents.saveEditError': 'Could not save',
  'incidents.loadError': 'Could not load incident',
  'incidents.statusError': 'Could not change status',
  'coordinatorRequests.title': 'Coordinator requests',
  'coordinatorRequests.subtitle': 'Manage requests: publish, assign, statuses',
  'coordinatorRequests.searchPlaceholder': 'Search...',
  'coordinatorRequests.unpublish': 'Unpublish',
  'coordinatorRequests.publish': 'Publish',
  'coordinatorRequests.assign': 'Assign',
  'coordinatorRequests.assignTitle': 'Assign volunteer — request {id}',
  'coordinatorRequests.volunteerSearch': 'Search volunteer...',
  'coordinatorRequests.assignBtn': 'Assign',
  'coordinatorRequests.loadingVolunteers': 'Loading volunteers...',
  'coordinatorRequests.noVolunteers': 'No volunteers',
  'coordinatorRequests.editTitle': 'Edit request {id}',
  'coordinatorRequests.editTitleLabel': 'Title (5–200 characters)',
  'coordinatorRequests.editDescLabel': 'Description (at least 50 characters)',
  'coordinatorRequests.problemType': 'Type of help',
  'coordinatorRequests.landmark': 'Landmark',
  'coordinatorRequests.contactPerson': 'Contact person',
  'coordinatorRequests.additionalInfo': 'Additional info',
  'coordinatorRequests.empty': 'No requests',
  'coordinatorRequests.publishError': 'Publish error',
  'coordinatorRequests.unpublishError': 'Unpublish error',
  'coordinatorRequests.loadError': 'Could not load request',
  'coordinatorRequests.saveError': 'Could not save request',
  'coordinatorRequests.assignError': 'Assignment error',
  'volunteers.title': 'Volunteers',
  'volunteers.subtitle': 'Search volunteers and assign them (assignment is in “Requests”)',
  'volunteers.searchPlaceholder': 'Search by name, email, phone...',
  'volunteers.thName': 'Name',
  'volunteers.thPhone': 'Phone',
  'volunteers.thCount': 'Requests',
  'volunteers.assignToRequest': 'Assign to request',
  'volunteers.empty': 'No volunteers',
  'volunteerTasks.title': 'My tasks',
  'volunteerTasks.subtitle': 'Available requests to join and requests you are assigned to',
  'volunteerTasks.allPriorities': 'All priorities',
  'volunteerTasks.allTypes': 'All types',
  'volunteerTasks.allDistricts': 'All districts',
  'volunteerTasks.allStatuses': 'All statuses',
  'volunteerTasks.available': 'Available',
  'volunteerTasks.assigned': 'My assignments',
  'volunteerTasks.people': 'People: {n}',
  'volunteerTasks.alreadyResponded': 'You already responded',
  'volunteerTasks.leave': 'Leave request',
  'volunteerTasks.emptyAvailable': 'No available requests',
  'volunteerTasks.emptyAssigned': 'You are not assigned to any request yet',
  'volunteerTasks.respondError': 'Could not respond',
  'volunteerTasks.leaveError': 'Could not leave',
  'admin.usersTitle': 'Users',
  'admin.requestsTitle': 'Requests',
  'admin.incidentsTitle': 'Incidents',
  'admin.overview': 'Overview',
  'admin.users': 'Users',
  'admin.unverified': 'Unverified: {n}',
  'admin.requests': 'Requests',
  'admin.published': 'Published: {n}',
  'admin.incidents': 'Incidents',
  'admin.activeIncidents': 'Active: {n}',
  'admin.usersByRole': 'Users by role',
  'admin.requestsByStatus': 'Requests by status',
  'admin.userTitle': 'User {id}',
  'admin.userNotFound': 'User not found',
  'admin.editing': 'Editing',
  'admin.changeRole': 'Change role',
  'admin.changeRoleBtn': 'Change role',
  'admin.deleteUser': 'Delete user',
  'admin.deleteUserConfirm': 'Delete this user?',
  'admin.roleChanged': 'Role updated',
  'admin.requestTitle': 'Request {id}',
  'admin.requestNotFound': 'Request not found',
  'admin.publishedLabel': 'Published',
  'admin.changeStatus': 'Change status',
  'admin.unpublish': 'Unpublish',
  'admin.deleteRequest': 'Delete request',
  'admin.deleteRequestConfirm': 'Delete this request?',
  'admin.statusChanged': 'Status updated',
  'admin.publishedMsg': 'Published',
  'admin.unpublishedMsg': 'Unpublished',
  'admin.incidentTitle': 'Incident {id}',
  'admin.incidentNotFound': 'Incident not found',
  'admin.statusChange': 'Change status',
  'admin.deleteIncident': 'Delete incident',
  'admin.deleteIncidentConfirm': 'Delete this incident?',
  'admin.newIncident': 'New incident',
  'admin.level': 'Level',
  'admin.createIncidentError': 'Create error',
  'admin.allRoles': 'All roles',
  'admin.emptyUsers': 'No users',
  'admin.emptyRequests': 'No requests',
  'admin.emptyIncidents': 'No incidents',
  'roles.default': 'User',
  'roles.USER': 'User',
  'roles.VOLUNTEER': 'Volunteer',
  'roles.COORDINATOR': 'Coordinator',
  'roles.ADMIN': 'Administrator',
  'client.reauth': 'Please sign in again',
  'enums.problemType.MEDICAL': 'Medical aid',
  'enums.problemType.FOOD': 'Food',
  'enums.problemType.EVACUATION': 'Evacuation',
  'enums.problemType.SHELTER': 'Shelter / housing',
  'enums.problemType.REPAIR': 'Repairs',
  'enums.problemType.PSYCHOLOGICAL': 'Psychological support',
  'enums.priority.CRITICAL': 'Critical',
  'enums.priority.HIGH': 'High',
  'enums.priority.MEDIUM': 'Medium',
  'enums.priority.LOW': 'Low',
  'enums.district.ALMALYNSKIY': 'Almaly district',
  'enums.district.AUEZOVSKIY': 'Auezov district',
  'enums.district.BOSTANDYQ': 'Bostandyq district',
  'enums.district.MEDEU': 'Medeu district',
  'enums.district.NAURYZBAY': 'Nauryzbay district',
  'enums.district.TURKSIB': 'Turksib district',
  'enums.district.ZHETYSU': 'Zhetysu district',
  'enums.district.ALATAU': 'Alatau district',
  'enums.requestStatus.NEW': 'New',
  'enums.requestStatus.IN_PROGRESS': 'In progress',
  'enums.requestStatus.DONE': 'Done',
  'enums.requestStatus.CANCELLED': 'Cancelled',
  'enums.requestStatusShort.NEW': 'New',
  'enums.requestStatusShort.IN_PROGRESS': 'In progress',
  'enums.requestStatusShort.DONE': 'Done',
  'enums.requestStatusShort.CANCELLED': 'Cancelled',
  'enums.severity.CRITICAL': 'Critical',
  'enums.severity.HIGH': 'High',
  'enums.severity.MEDIUM': 'Medium',
  'enums.severity.LOW': 'Low',
  'enums.incidentStatus.ACTIVE': 'Active',
  'enums.incidentStatus.RESOLVING': 'Resolving',
  'enums.incidentStatus.RESOLVED': 'Resolved',
  'validation.emailRequired': 'Email is required',
  'validation.emailInvalid': 'Enter a valid email',
  'validation.passwordRequired': 'Password is required',
  'validation.passwordMinLength': 'Password must be at least 8 characters',
  'validation.passwordUppercase': 'At least one uppercase letter is required',
  'validation.passwordDigit': 'At least one digit is required',
  'validation.passwordSpecial': 'At least one special character is required',
  'validation.phoneRequired': 'Phone is required',
  'validation.phoneInvalid': 'Enter a valid phone number',
  'validation.firstNameRequired': 'First name is required',
  'validation.firstNameMin': 'First name must be at least 2 characters',
  'validation.lastNameRequired': 'Last name is required',
  'validation.lastNameMin': 'Last name must be at least 2 characters',
  'validation.fieldRequired': 'This field is required',
  'validation.fieldMin': 'Must be at least 2 characters',
  'validation.passwordsMismatch': 'Passwords do not match',
  'validation.roleRequired': 'Select a role',
  'validation.problemTypeRequired': 'Select a problem type',
  'validation.problemTypeInvalid': 'Invalid problem type',
  'validation.priorityRequired': 'Select a priority',
  'validation.priorityInvalid': 'Invalid priority',
  'validation.districtRequired': 'Select a district',
  'validation.districtInvalid': 'Invalid district',
  'validation.titleRequired': 'Title is required',
  'validation.titleLength': 'Title: 5–200 characters',
  'validation.descriptionRequired': 'Description is required',
  'validation.descriptionMin': 'Description must be at least 50 characters',
  'validation.addressRequired': 'Enter an address',
  'validation.incidentDescriptionMin': 'Description: minimum 20 characters',
  'validation.severityRequired': 'Select severity',
  'map.address': 'Address',
  'myRequests.thTitle': 'Title',
  'myRequests.thType': 'Type',
  'myRequests.thPriority': 'Priority',
  'myRequests.thDistrict': 'District',
  'myRequests.thStatus': 'Status',
  'myRequests.thPublished': 'Publication',
  'incidents.allDistricts': 'All districts',
  'incidents.thTitle': 'Title',
  'incidents.thDistrict': 'District',
  'incidents.thStatus': 'Status',
  'incidents.thActions': 'Actions',
  'coordinatorRequests.allStatuses': 'All statuses',
  'coordinatorRequests.allPriorities': 'All priorities',
  'coordinatorRequests.allTypes': 'All types',
  'coordinatorRequests.allDistricts': 'All districts',
  'coordinatorRequests.thPublished': 'Publication',
  'coordinatorRequests.thActions': 'Actions',
  'coordinatorRequests.statusError': 'Could not change status',
  'volunteers.allDistricts': 'All districts',
  'volunteers.thDistrict': 'District',
  'admin.actions': 'Actions',
}

/** Kazakh: Russian base (ru) + these overrides — expand over time for full coverage */
const kkOverrides = {
  'a11y.languageMenu': 'Тіл таңдау',
  'a11y.openMenu': 'Мәзірді ашу',
  'a11y.close': 'Жабу',
  'nav.features': 'Мүмкіндіктер',
  'nav.howItWorks': 'Қалай жұмыс істейді',
  'nav.about': 'Платформа туралы',
  'nav.profile': 'Профиль',
  'nav.logout': 'Шығу',
  'nav.login': 'Кіру',
  'nav.register': 'Тіркелу',
  'nav.dashboard': 'Бақылау тақтасы',
  'nav.map': 'Карта',
  'nav.createRequest': 'Сұраныс жасау',
  'nav.myRequests': 'Менің сұраныстарым',
  'nav.requests': 'Сұраныстар',
  'nav.volunteers': 'Еріктілер',
  'nav.incidents': 'Оқиғалар',
  'nav.myTasks': 'Менің тапсырмаларым',
  'nav.admin': 'Әкімшілік',
  'nav.adminOverview': 'Шолу',
  'nav.adminUsers': 'Пайдаланушылар',
  'nav.adminRequests': 'Сұраныстар',
  'nav.adminIncidents': 'Оқиғалар',
  'nav.mainSite': 'Негізгі сайтқа',
  'footer.tagline': 'Төтенше жағдайларда көмек үйлестіру платформасы',
  'footer.platform': 'Платформа',
  'footer.roles': 'Рөлдер',
  'footer.contacts': 'Байланыс',
  'footer.copyright': '© 2026 DisasterHelp. Барлық құқықтар қорғалған.',
  'home.heroLine1': 'Жедел көмек үйлестіру',
  'home.heroLine2': 'төтенше жағдайларда',
  'home.createHelp': 'Көмек сұранысын жасау',
  'home.becomeVolunteer': 'Ерікті болу',
  'common.save': 'Сақтау',
  'common.cancel': 'Болдырмау',
  'common.close': 'Жабу',
  'common.loading': 'Жүктелуде...',
  'auth.signIn': 'Кіру',
  'auth.registerTitle': 'Аккаунт жасау',
  'roles.USER': 'Пайдаланушы',
  'roles.VOLUNTEER': 'Ерікті',
  'roles.COORDINATOR': 'Үйлестіруші',
  'roles.ADMIN': 'Әкімші',
  'validation.emailRequired': 'Email міндетті',
  'validation.passwordRequired': 'Құпия сөз міндетті',
  'map.address': 'Мекенжай',
  'myRequests.thTitle': 'Тақырып',
  'myRequests.thType': 'Түрі',
  'myRequests.thPriority': 'Басымдық',
  'myRequests.thDistrict': 'Аудан',
  'myRequests.thStatus': 'Күйі',
  'myRequests.thPublished': 'Жариялау',
  'incidents.allDistricts': 'Барлық аудандар',
  'incidents.thTitle': 'Тақырып',
  'incidents.thDistrict': 'Аудан',
  'incidents.thStatus': 'Күйі',
  'incidents.thActions': 'Әрекеттер',
  'coordinatorRequests.allStatuses': 'Барлық күйлер',
  'coordinatorRequests.allPriorities': 'Барлық басымдықтар',
  'coordinatorRequests.allTypes': 'Барлық түрлер',
  'coordinatorRequests.allDistricts': 'Барлық аудандар',
  'coordinatorRequests.thPublished': 'Жариялау',
  'coordinatorRequests.thActions': 'Әрекеттер',
  'coordinatorRequests.statusError': 'Күйді өзгерту қатесі',
  'volunteers.allDistricts': 'Барлық аудандар',
  'volunteers.thDistrict': 'Аудан',
  'admin.actions': 'Әрекеттер',
}

for (const [path, val] of Object.entries(enOverrides)) {
  en[path] = val
}
for (const [path, val] of Object.entries(kkOverrides)) {
  kk[path] = val
}

const enOut = applyOverrides(ru, en)
const kkOut = applyOverrides(ru, kk)

fs.writeFileSync(join(root, 'src/locales/en.json'), JSON.stringify(enOut, null, 2), 'utf8')
fs.writeFileSync(join(root, 'src/locales/kk.json'), JSON.stringify(kkOut, null, 2), 'utf8')
console.log('en.json and kk.json written')
